name: Build and Release FH6Auto

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'

    - name: Install Dependencies
      run: |
        chcp 65001
        python -m pip install --upgrade pip
        if (Test-Path -Path "requirements.txt") { pip install -r requirements.txt }
        pip install nuitka

    - name: Nuitka Build
      run: |
        chcp 65001
        python -m nuitka --standalone --windows-uac-admin --assume-yes-for-downloads --output-dir=build_out main.py



    - name: Inno Setup Build
      run: |
        chcp 65001
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "/DAppVersion=${env:APP_VERSION}" build_installer.iss

    - name: Publish to GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Release/FH6Auto_Installer_v*.exe
        name: Release v${{ env.APP_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
